# Dependencies
markdown            : kramdown
redcarpet:
  extensions        : ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]
highlighter         : rouge
gems                : ["jekyll-paginate", "jekyll-asciidoc"]

# Permalinks
permalink           : pretty

# Setup
title               : "Shihta's Note"
tagline             : 'tag line'
description         : 'descriptions'
baseurl             : /

author              : Shihta Kuan
name                : 'Shihta Kuan'
url                 : https://shihta.github.io/

paginate            : 5

# Custom vars
version             : 0.1.0
github_username     : Shihta
